let indexe = 0;
const limiteporvez = 1;
const resultado = document.getElementById('video');
const botao = document.getElementById('btn');
let contador = 0;
const videos = [
  // seus links de vídeos aqui
                      'https://www.youtube.com/embed/gmz8zlvgjxA',
                      "https://www.youtube.com/embed/fs7JoMcNqo8",
                      'https://www.youtube.com/embed/hLrNckEmcAc',
                      'https://www.youtube.com/embed/SdVa3emdxe4',
                      'https://www.youtube.com/embed/BprkK7-o-QY',
                      'https://www.youtube.com/embed/XLlwB02WlZI',
                      'https://www.youtube.com/embed/aWrYEHpjX-M',
                      'https://www.youtube.com/embed/cQXnTBbGXCE',
                      'https://www.youtube.com/embed/usw0YtRTT1E',
                      'https://www.youtube.com/embed/NzVCiLvOWI8',
                      'https://www.youtube.com/embed/lmm9iKoSpHc',
                      'https://www.youtube.com/embed/1zjV3h7gZak',
                      'https://www.youtube.com/embed/VVLQw0EIfbY',
                      'https://www.youtube.com/embed/cKpxBF8fMlw',
                      'https://www.youtube.com/embed/CbL86HdTJo4',
                      'https://www.youtube.com/embed/h0kh4zb9GWc',
                      'https://www.youtube.com/embed/prWFhlMZyeQ',
                      'https://www.youtube.com/embed/q_VNIc7BY6I',
                      'https://www.youtube.com/embed/TphJ6eR1nG4',
                      'https://www.youtube.com/embed/jmru5B2LxVA',
                      'https://www.youtube.com/embed/IwChHlQcic0',
                      'https://www.youtube.com/embed/E90VafLZXr4',
                      'https://www.youtube.com/embed/PECdUzyKMxc',
                      'https://www.youtube.com/embed/ksfjqSoSVOE',
                      'https://www.youtube.com/embed/7nlncLNblMM',
                      'https://www.youtube.com/embed/N3ZN5k7nl3k',
                      'https://www.youtube.com/embed/5CDpEKvcdhU',
                      'https://www.youtube.com/embed/a0cI1DQcY74',
                      'https://www.youtube.com/embed/YKmMFJ1xiz0',
                      'https://www.youtube.com/embed/OcxVNbeK9oo',
                      'https://www.youtube.com/embed/4KTL_9X8MU0',
                      'https://www.youtube.com/embed/bQgMghpk6jU',
                      'https://www.youtube.com/embed/UTqBUUTgfgg',
                      'https://www.youtube.com/embed/kW9oZBxWsFM',
                      'https://www.youtube.com/embed/Dbiid_gHhMA',
                      'https://www.youtube.com/embed/gA7YqEtWwWw',
                      'https://www.youtube.com/embed/w4kkChMmfDE',
                      'https://www.youtube.com/embed/RIc2gIAWd-E',
                      'https://www.youtube.com/embed/wnjE8Dkjo38',
                      'https://www.youtube.com/embed/m7ElAh4F7Ts',
                      'https://www.youtube.com/embed/q1tGIyQMdg8',
                      'https://www.youtube.com/embed/ERAENuba_TA',
                      'https://www.youtube.com/embed/ZTREW0aoqCY',
                      'https://www.youtube.com/embed/BZb76PJAc3Q',
                      'https://www.youtube.com/embed/T9fRfG0njdE',
                      'https://www.youtube.com/embed/R1T2PiHriJc',
                      'https://www.youtube.com/embed/8FTi4M82soQ',
                      'https://www.youtube.com/embed/8O3qjdm3m40',
                      'https://www.youtube.com/embed/azyDKOFY3hQ',
                      'https://www.youtube.com/embed/HuVxK_8zR20',
          'https://www.youtube.com/embed/T6sYp_FrpCA',
          'https://www.youtube.com/embed/S-Z1l1U5Svg',
          'https://www.youtube.com/embed/zT4aYS4Gm3A',
          'https://www.youtube.com/embed/MfCnnfl54Co',
          'https://www.youtube.com/embed/wAHB4WJliNo',
          'https://www.youtube.com/embed/Ttp06RN7jTc',
          'https://www.youtube.com/embed/6oRsaU94iXI',
          'https://www.youtube.com/embed/WsSJPJ4BSaw',
          'https://www.youtube.com/embed/fpEkB3KfQPo',
          'https://www.youtube.com/embed/MAax7771cUw',
          'https://www.youtube.com/embed/JstdH-c0e2g',
          'https://www.youtube.com/embed/B3i4xYTaJ7Q',
          'https://www.youtube.com/embed/MIvrS5aKing',
          'https://www.youtube.com/embed/IIKSKIyFE1o',
          'https://www.youtube.com/embed/SeRcYE6AP_0',
          'https://www.youtube.com/embed/FKa9tlyZiMo',
          'https://www.youtube.com/embed/PCgDwc2Rw-U',
          'https://www.youtube.com/embed/JfK8rUMPRcU',
          'https://www.youtube.com/embed/LsEFaDkJfKQ',
          'https://www.youtube.com/embed/T6sYp_FrpCA',
          'https://www.youtube.com/embed/69aVw9a4wy0',
          'https://www.youtube.com/embed/wj1TDk061xU',
          'https://www.youtube.com/embed/N5XsyB9oimo',
          'https://www.youtube.com/embed/0nOA9e-gMMA',
          'https://www.youtube.com/embed/OZYyOzuHGwM',
          'https://www.youtube.com/embed/hlR0KZFPiQM',
          'https://www.youtube.com/embed/QF-89rauJ5E',
          'https://www.youtube.com/embed/pcrAtkvGIAM',
          'https://www.youtube.com/embed/4GRz73uaSro',
          'https://www.youtube.com/embed/HPYguwJ6GQw',
          'https://www.youtube.com/embed/tYrdaMO--mI',
          'https://www.youtube.com/embed/xZ6V4wnde9U',
          'https://www.youtube.com/embed/kvcwy_KYlYI',
          'https://www.youtube.com/embed/1G1gQ7ztnno',
          'https://www.youtube.com/embed/IMX222PNZkQ',
          'https://www.youtube.com/embed/3kCOuuGwUM8',
          'https://www.youtube.com/embed/1RPFPaw3vSA',
          'https://www.youtube.com/embed/e6HIBWV4WP4',
          'https://www.youtube.com/embed/EWXtDuDvRJc',
          'https://www.youtube.com/embed/LI4G5bEaeDQ',
          'https://www.youtube.com/embed/sKYXWBvgPM8',
          'https://www.youtube.com/embed/-YAk86n0sno',
          'https://www.youtube.com/embed/5YK2rbkJfmM',
          'https://www.youtube.com/embed/ewRJ0n3LmaY',
          'https://www.youtube.com/embed/UIoVIVtNg0w',
          'https://www.youtube.com/embed/_H7DZUZubz8',
          'https://www.youtube.com/embed/hpPaAx7SszU',
          'https://www.youtube.com/embed/_xrm7T4ZOEc',
          'https://www.youtube.com/embed/1XgMGqbikE4',
          'https://www.youtube.com/embed/TZDh-p_pj-k',
          'https://www.youtube.com/embed/pS8Fe7v0tus',
          'https://www.youtube.com/embed/BXYCwgVzK4Y',
          'https://www.youtube.com/embed/gdkGqTwyfxo',
          'https://www.youtube.com/embed/4QOIZXJbrDQ',
          'https://www.youtube.com/embed/GSXpLh41ZZY',
          'https://www.youtube.com/embed/pgpr25qdv9g',
          'https://www.youtube.com/embed/qTTN0wXfDDQ',
          'https://www.youtube.com/embed/ki304lC6fxQ',
          'https://www.youtube.com/embed/mz7GlswJ6P4',
          'https://www.youtube.com/embed/p7UHErfMpik',
          'https://www.youtube.com/embed/u-TaToZdFnQ',
          'https://www.youtube.com/embed/ypRQ8PK1QTo',
          'https://www.youtube.com/embed/SIwlB0cYdHk',
          'https://www.youtube.com/embed/gQDblkZeVwc',
          'https://www.youtube.com/embed/cvEa_8eiNow',
          'https://www.youtube.com/embed/9Y-xZjmLI2Q',
          'https://www.youtube.com/embed/1_xTXY2OUCQ',
          'https://www.youtube.com/embed/-ufrSS9HZzw',
          'https://www.youtube.com/embed/7bWx69W09sQ',
          'https://www.youtube.com/embed/yO979VXVMjA',
          'https://www.youtube.com/embed/oJnNfLEMTaI',
          'https://www.youtube.com/embed/TjoiX00jbYg',
          'https://www.youtube.com/embed/ZCwN9cEgL58',
          'https://www.youtube.com/embed/4uuPF6voBjI',
          'https://www.youtube.com/embed/wlsN2wVzt5Y',
          'https://www.youtube.com/embed/5YH3g9FuVjE',
          'https://www.youtube.com/embed/oQUv3IrnQEM',
          'https://www.youtube.com/embed/VUVkbLkb6mw',
          'https://www.youtube.com/embed/U51F3Nn2Bws',
          'https://www.youtube.com/embed/aHpmf57_PE4',
          'https://www.youtube.com/embed/1BU6AhnBNTs',
          'https://www.youtube.com/embed/C3IcX-vtOgA',
          'https://www.youtube.com/embed/2RfX-oHf9Ns',
          'https://www.youtube.com/embed/RGCC9tq63qY',
          'https://www.youtube.com/embed/_ktd4MbEDFk',
          'https://www.youtube.com/embed/HJnF1kuKC4E',
          'https://www.youtube.com/embed/jNB-Ii5F3Ok',
          'https://www.youtube.com/embed/kuy44vkfb9g',
          'https://www.youtube.com/embed/b4ldDONIqLo',
          'https://www.youtube.com/embed/XzfcLS5bU_k',
          'https://www.youtube.com/embed/Ps9vawzaGvc',
          'https://www.youtube.com/embed/PfXGl2Fxrgo',
          'https://www.youtube.com/embed/kCNmK6xH8LI',
          'https://www.youtube.com/embed/a4ilDzcftTc',
          'https://www.youtube.com/embed/acGRh4QOjw0',
          'https://www.youtube.com/embed/5FQ4AuyG2No',
          'https://www.youtube.com/embed/SqAqSxQJYHs',
          'https://www.youtube.com/embed/OHWmSpcLDOs',
          'https://www.youtube.com/embed/Gh_7SK5CkrE',
          'https://www.youtube.com/embed/6qYLLnim9kY',
          'https://www.youtube.com/embed/WDlIHAPUXBk',
          'https://www.youtube.com/embed/j4g7_GsBwwk',
          'https://www.youtube.com/embed/Qxc1pNEblEg',
          'https://www.youtube.com/embed/TVqZHAPu8B4',
          'https://www.youtube.com/embed/k-mEFn6c7rY',
          'https://www.youtube.com/embed/GSMM6aObWwY',
          'https://www.youtube.com/embed/fxSTAEpKBuY',
          'https://www.youtube.com/embed/xgHvlxRSNWg',
          'https://www.youtube.com/embed/67NaM8j8dOQ',
          'https://www.youtube.com/embed/rflaqgFDzio',
          'https://www.youtube.com/embed/iI4qnu6d9Pc',
          'https://www.youtube.com/embed/wfcnOe_K3Hs',
          'https://www.youtube.com/embed/x_kA6GdS6sw',
          'https://www.youtube.com/embed/9Vk5X2wW4gQ',
          'https://www.youtube.com/embed/_Cw3LeKhvVA',
          'https://www.youtube.com/embed/QC2GvFVOJWE',
          'https://www.youtube.com/embed/r4puFLU3ZUE',
          'https://www.youtube.com/embed/iddS9_MgJKw',
          'https://www.youtube.com/embed/tc9Z0bK872M',
          'https://www.youtube.com/embed/KIlqmv67jK4',
          'https://www.youtube.com/embed/y26hMB9BR-Q',
          'https://www.youtube.com/embed/CKRRrySzQTo',
          'https://www.youtube.com/embed/e6y55D_KecM',
          'https://www.youtube.com/embed/4kCuladpuKI',
          'https://www.youtube.com/embed/-HfCF8mkzUc',
          'https://www.youtube.com/embed/b1JR_SYyJXU',
          'https://www.youtube.com/embed/nG1ySVpJvYk',
          'https://www.youtube.com/embed/JyPYhsiMsxg',
          'https://www.youtube.com/embed/HmOYLXCgqvM',
          'https://www.youtube.com/embed/JXK61sDWTs0',
          'https://www.youtube.com/embed/Qkf777v9q2c',
          'https://www.youtube.com/embed/3BkXV0TPRx4',
          'https://www.youtube.com/embed/PAElRV-lUgE',
          'https://www.youtube.com/embed/LjG_MBfAJAk',
          'https://www.youtube.com/embed/GphYMh4Vn0M',
          'https://www.youtube.com/embed/HiDmNXnr1Lk',
          'https://www.youtube.com/embed/380FrtwfNvw',
          'https://www.youtube.com/embed/uQ_oM4KNkPQ',
          'https://www.youtube.com/embed/G1zYtJ0_SXc',
          'https://www.youtube.com/embed/JO5G3hKRSw0',
          'https://www.youtube.com/embed/slENdG764I4',
          'https://www.youtube.com/embed/rKtEB0hnfLI',
          'https://www.youtube.com/embed/bCZLPqoouqs',
          'https://www.youtube.com/embed/m8GzLcAvKoA',
          'https://www.youtube.com/embed/0yn1m4vtyIU',
          'https://www.youtube.com/embed/EQJsz1fk5Tc',
          'https://www.youtube.com/embed/zA_kOUxJREY',
          'https://www.youtube.com/embed/ban0XqghI_E',
          'https://www.youtube.com/embed/cTbv3AO_JwQ',
          'https://www.youtube.com/embed/4V642gY5I78',
          'https://www.youtube.com/embed/bT9ICVJSxZg',
          'https://www.youtube.com/embed/4AcjKjKyyOc',
          'https://www.youtube.com/embed/AV-jYKJipX4',
          'https://www.youtube.com/embed/JyPYhsiMsxg',
          'https://www.youtube.com/embed/TH19SjxIqiY',
          'https://www.youtube.com/embed/HgoYhPLymEo',
          'https://www.youtube.com/embed/y6g6YaR_CBA',
          'https://www.youtube.com/embed/ct0c3-3HdlY',
          'https://www.youtube.com/embed/Ew-0dtk8BGY',
          'https://www.youtube.com/embed/-hC35stB1V8',
          'https://www.youtube.com/embed/EruqNMGipig',
          'https://www.youtube.com/embed/-iFkdrVURlE',
          'https://www.youtube.com/embed/fsd-hINR34Q',
          'https://www.youtube.com/embed/G_5rE1DCBQ8',
          'https://www.youtube.com/embed/4tR7g-Ep2Xk',
          'https://www.youtube.com/embed/42e5SeSnmR8',
          'https://www.youtube.com/embed/W8lmQ2-QH9A',
          'https://www.youtube.com/embed/dBCLcHnqwOM',
          'https://www.youtube.com/embed/DdsjD0XtjQ4',
          'https://www.youtube.com/embed/ooJZCb8RChg',
          'https://www.youtube.com/embed/YBLcjDzs71c',
          'https://www.youtube.com/embed/ClQNL3egTJw',
          'https://www.youtube.com/embed/fRvGe9pHH_k',
          'https://www.youtube.com/embed/ebSZ0_K5FQw',
          'https://www.youtube.com/embed/eBdJ9ywMpNk',
          'https://www.youtube.com/embed/2sc8YqJNCSw',
          'https://www.youtube.com/embed/HpZ9JsR0D0I',
          'https://www.youtube.com/embed/Cmype7kLMtI',
          'https://www.youtube.com/embed/aeXcvnehFnI',
          'https://www.youtube.com/embed/TwxWg7zzRYg',
          'https://www.youtube.com/embed/zT5ynWYBp5U',
          'https://www.youtube.com/embed/fBhjEZBEHRs',
          'https://www.youtube.com/embed/kKpYgPw_baM',
          'https://www.youtube.com/embed/_PpmYjq4cpE',
          'https://www.youtube.com/embed/WdWHNTxqaFI',
          'https://www.youtube.com/embed/qsN9UwF4eMA',
          'https://www.youtube.com/embed/EeUUBqw0vm0',
          'https://www.youtube.com/embed/tDNWJR2XbKA',
          'https://www.youtube.com/embed/rb85p-h5usk',
          'https://www.youtube.com/embed/mHm5qE1Gbik',
          'https://www.youtube.com/embed/0Z5LEAK8vAM',
          'https://www.youtube.com/embed/EXVSzvo_7OA',
            'https://www.youtube.com/embed/vOZQTPXs_sQ',
            'https://www.youtube.com/embed/t2UUarVLr04',
            'https://www.youtube.com/embed/9KxdA0XW_Lg',
            'https://www.youtube.com/embed/1-dKnVALkrI',
            'https://www.youtube.com/embed/S9S8bbe3IOY',
            'https://www.youtube.com/embed/-EbgQh6gzTA',
            'https://www.youtube.com/embed/1zjV3h7gZak',
            'https://www.youtube.com/embed/4azDsWGCqfM',
            'https://www.youtube.com/embed/lMlZYY-u8s8',
            'https://www.youtube.com/embed/jzm7WKICCwc',
            'https://www.youtube.com/embed/u5bycrIqqMQ',
            'https://www.youtube.com/embed/Bt_ZamVkkRA',
            'https://www.youtube.com/embed/CowwBYVPy4o',
            'https://www.youtube.com/embed/qo1Ay1XTUzU',
            'https://www.youtube.com/embed/6MZqdVOBOMg',
            'https://www.youtube.com/embed/cnkpgVvHneA',
            'https://www.youtube.com/embed/G_uQySmgUOg',
            'https://www.youtube.com/embed/grMZ2YyRyQQ',
            'https://www.youtube.com/embed/9xVksHAYy8Y',
            'https://www.youtube.com/embed/ZTREW0aoqCY',
            'https://www.youtube.com/embed/KnTUv3vuXU4',
            'https://www.youtube.com/embed/34nrFy_7YFs',
            'https://www.youtube.com/embed/6eWs69ijA4I',
            'https://www.youtube.com/embed/lMlZYY-u8s8',
            'https://www.youtube.com/embed/jzm7WKICCwc',
            'https://www.youtube.com/embed/u5bycrIqqMQ',
            'https://www.youtube.com/embed/Bt_ZamVkkRA',
            'https://www.youtube.com/embed/CowwBYVPy4o',
            'https://www.youtube.com/embed/ZTREW0aoqCY',
            'https://www.youtube.com/embed/qo1Ay1XTUzU',
            'https://www.youtube.com/embed/6MZqdVOBOMg',
            'https://www.youtube.com/embed/cnkpgVvHneA',
            'https://www.youtube.com/embed/G_uQySmgUOg',
            'https://www.youtube.com/embed/grMZ2YyRyQQ',
            'https://www.youtube.com/embed/9xVksHAYy8Y',
            'https://www.youtube.com/embed/KnTUv3vuXU4',
            'https://www.youtube.com/embed/34nrFy_7YFs',
            'https://www.youtube.com/embed/6eWs69ijA4I',
            'https://www.youtube.com/embed/mF_lLfVrd4c',
            'https://www.youtube.com/embed/3z-ywevbmEw',
            'https://www.youtube.com/embed/QLHncQGorTQ',
            'https://www.youtube.com/embed/F4pSxeLGT3U',
            'https://www.youtube.com/embed/_5SyS7bzQPQ',
            'https://www.youtube.com/embed/sTDd61CUCzQ',
            'https://www.youtube.com/embed/rDblGRyiKKU',
            'https://www.youtube.com/embed/515o-VG3bG8',
            'https://www.youtube.com/embed/NZVUz43oZTg',
            'https://www.youtube.com/embed/kFy_Za822m4',
            'https://www.youtube.com/embed/xqvstjXYacU',
            'https://www.youtube.com/embed/MBT8vxuBkmU',
            'https://www.youtube.com/embed/6Q-WzhrcndM',
            'https://www.youtube.com/embed/W45p4dT4McY',
            'https://www.youtube.com/embed/TY3MiQXO28U',
            'https://www.youtube.com/embed/sSvd74NVl3o',
            'https://www.youtube.com/embed/2GLzhokW8Hc',
            'https://www.youtube.com/embed/Yydiex6Z8qA',
            'https://www.youtube.com/embed/0f6YUbUr5nc',
            'https://www.youtube.com/embed/CGJ2Q0jM8mA',
            'https://www.youtube.com/embed/5GCPtNnglNA',
            'https://www.youtube.com/embed/Ur6DP11zAv0',
            'https://www.youtube.com/embed/3bD-XAYVmrk',
            'https://www.youtube.com/embed/hP7mDRJBiow',
            'https://www.youtube.com/embed/qtHCIBDKSIk',
            'https://www.youtube.com/embed/as3vR8UG86I',
            'https://www.youtube.com/embed/BZIxKwQnUXI',
            'https://www.youtube.com/embed/55bTuciaN5s',
            'https://www.youtube.com/embed/Fm56JkpimvQ',
            'https://www.youtube.com/embed/5iSK9iJZf80',
            'https://www.youtube.com/embed/LXRH8jMu1g0',
            'https://www.youtube.com/embed/Ji70oFphEm0',
            'https://www.youtube.com/embed/Zkcm4sRrAtw',
            'https://www.youtube.com/embed/odOJDBOaKsQ',
            'https://www.youtube.com/embed/8yvf5d3cttk',
            'https://www.youtube.com/embed/_EYfg0ckMjo',
            'https://www.youtube.com/embed/ojWl5kQ7GjY',
            'https://www.youtube.com/embed/Ur6DP11zAv0',
            'https://www.youtube.com/embed/RU9xzRNSYpQ',
            'https://www.youtube.com/embed/NLgWp5vxXJM',
            'https://www.youtube.com/embed/5czjXpukJHs',
            'https://www.youtube.com/embed/PfbOYzOUqvc',
            'https://www.youtube.com/embed/1ONt7hF0Ir8',
            'https://www.youtube.com/embed/xsdov8-Onig',
            'https://www.youtube.com/embed/bB8-VRGFea8',
            'https://www.youtube.com/embed/tGq9ffvt8EM',
            'https://www.youtube.com/embed/754Qp0ChTgA',
            'https://www.youtube.com/embed/NFxHKDBv8ns',
            'https://www.youtube.com/embed/IB36Rqf4SB8',
            'https://www.youtube.com/embed/PaGd4vJ9tvc',
            'https://www.youtube.com/embed/rm7N0p9Vy6Q',
            'https://www.youtube.com/embed/4jbd1Hhuacs',
            'https://www.youtube.com/embed/ZOiuUwDxdHY',
            'https://www.youtube.com/embed/2B7E1hqaino',
            'https://www.youtube.com/embed/3mPkaC7ZPjM',
            'https://www.youtube.com/embed/JExf-m6d2D4',
            'https://www.youtube.com/embed/p0Oh7X4WqiU',
            'https://www.youtube.com/embed/jh6GdVn2E4E',
            'https://www.youtube.com/embed/2o0WB3kwNeo',
            'https://www.youtube.com/embed/5smcDc1xVtM',
            'https://www.youtube.com/embed/A1L5vPaIsEE',
            'https://www.youtube.com/embed/ssEW6Iz7H3o',
            'https://www.youtube.com/embed/SMz1Rw68grc',
            'https://www.youtube.com/embed/Zs47BH1-EWU',
            'https://www.youtube.com/embed/grud8AK7vSo',
    "https://www.youtube.com/embed/Z6DxwnMKUhk",
    "https://www.youtube.com/embed/IakKjumw3Yo",
    "https://www.youtube.com/embed/8MXoFqbBYns",
    "https://www.youtube.com/embed/kfHsbeKnQHs",
    "https://www.youtube.com/embed/-M98qe3ijWo",
    "https://www.youtube.com/embed/TqWvndxPH4A",
    "https://www.youtube.com/embed/7xLQFJ3t-Yw",
    "https://www.youtube.com/embed/qgPIy3RiYTU",
    "https://www.youtube.com/embed/YCY0YuqpjZs",
    "https://www.youtube.com/embed/dNeT_4R2IhY",
    "https://www.youtube.com/embed/Edz480YMHY4",
    "https://www.youtube.com/embed/vsgr3HGgTK0",
    "https://www.youtube.com/embed/qMZuH7IPKwY",
    "https://www.youtube.com/embed/HGugfrmktDQ",
    "https://www.youtube.com/embed/fxZVYCcDDu8",
    "https://www.youtube.com/embed/vvoweQeT_fI",
    "https://www.youtube.com/embed/MkJ3BiMXulY",
    "https://www.youtube.com/embed/QYSH8W53x94",
    "https://www.youtube.com/embed/uCZ25X1KxgM",
    "https://www.youtube.com/embed/M3JaiqwOkWY",
    "https://www.youtube.com/embed/PFFAu5hojGE",
    "https://www.youtube.com/embed/o70Mwpl3mUY",
    "https://www.youtube.com/embed/rADp36rwnKk",
    "https://www.youtube.com/embed/8F3Buml0riM",
    "https://www.youtube.com/embed/ex1HQ82OdCg",
    "https://www.youtube.com/embed/CNe6kIhA6dE",
    "https://www.youtube.com/embed/Xr_zu4vGvvM",
    "https://www.youtube.com/embed/-CKpiYVuUQo",
    "https://www.youtube.com/embed/q4Zv-hRbdN8",
    "https://www.youtube.com/embed/oM0IWyD5DDU",
    "https://www.youtube.com/embed/6G_clD0BhQo",
    "https://www.youtube.com/embed/DefB8RmAeUs",
    "https://www.youtube.com/embed/G-2ynNugHHo",
    "https://www.youtube.com/embed/ZhrlUWGhHU8",
    "https://www.youtube.com/embed/IQpdNteZDuU",
    "https://www.youtube.com/embed/40MBx3XV8e0",
    "https://www.youtube.com/embed/8tSU1sKt_LQ",
    "https://www.youtube.com/embed/XNBayHI_F-U",
    "https://www.youtube.com/embed/nLMUdehb0iE",
    "https://www.youtube.com/embed/aQlQ49_StJc",
    "https://www.youtube.com/embed/HHejuNo9Pws",
    "https://www.youtube.com/embed/Rg5p7tVVO-o",
    "https://www.youtube.com/embed/o-B4ODuVHaQ",
    "https://www.youtube.com/embed/TXN_r4Bwd6k",
    "https://www.youtube.com/embed/txpiWJmmMt4",
    "https://www.youtube.com/embed/0R6-zkdHu6s",
    "https://www.youtube.com/embed/rXGQP3KonfY",
    "https://www.youtube.com/embed/NiclMO5jt4o",
    "https://www.youtube.com/embed/pSGD-QpNJkM",
    "https://www.youtube.com/embed/fCLoGMQuXZo",
    "https://www.youtube.com/embed/uOVqozQWCW4",
    "https://www.youtube.com/embed/fs7JoMcNqo8",
    "https://www.youtube.com/embed/UfLb5ZIoGaE",
    "https://www.youtube.com/embed/RXSJDj2Q6sQ",
    "https://www.youtube.com/embed/ZA8odhpKMRY",
    "https://www.youtube.com/embed/6bhy1_OrL2A",
    "https://www.youtube.com/embed/QYhtr6ym_mw",
    "https://www.youtube.com/embed/PtchqDQdfK4",
    "https://www.youtube.com/embed/U0oQoSZy09E",
    "https://www.youtube.com/embed/HNbi3FAqYVM",
    "https://www.youtube.com/embed/uVRERL0t5ZE",
    "https://www.youtube.com/embed/DBUX3Q9xc_k",
    "https://www.youtube.com/embed/54xSQzpSGbg",
    "https://www.youtube.com/embed/eQV5fYmyeiU",
    "https://www.youtube.com/embed/ugWuZ7RCV-g",
    "https://www.youtube.com/embed/EhacUDcchIs",
    "https://www.youtube.com/embed/tnlzekfxftk",
    "https://www.youtube.com/embed/NPI2_GJgzm4",
    "https://www.youtube.com/embed/mxjLadywznQ",
    "https://www.youtube.com/embed/UIRH5TRNk-A",
    "https://www.youtube.com/embed/ibpXARfLIj8",
    "https://www.youtube.com/embed/eSRgRVx9ZjQ",
    "https://www.youtube.com/embed/xq1UFrh0p-Q",
    "https://www.youtube.com/embed/qg8d-M64lgc",
    "https://www.youtube.com/embed/8gUW4HxMJoU",
    "https://www.youtube.com/embed/yP5pYR-2taU",
    "https://www.youtube.com/embed/jMVFLG-zUKM",
    "https://www.youtube.com/embed/ePAE_HAzXBQ",
    "https://www.youtube.com/embed/E-5J1RfIUv0",
    "https://www.youtube.com/embed/9gynQNOxRZc",
    "https://www.youtube.com/embed/vQmbXh_OPaY",
    "https://www.youtube.com/embed/BFYouBT7TmA",
    "https://www.youtube.com/embed/cHLsgk7J-yo",
    "https://www.youtube.com/embed/17D8AlzwKgE",
    "https://www.youtube.com/embed/VPBaPorlNtM",
    "https://www.youtube.com/embed/_AOhb6YCRlA",
    "https://www.youtube.com/embed/suZxmFreQ-k",
    "https://www.youtube.com/embed/l3bsUmm3vFk",
    "https://www.youtube.com/embed/3oVxi_Q2MJI",
    "https://www.youtube.com/embed/9BNJdU0sO90",
    "https://www.youtube.com/embed/_YWs4UXWTUw",
    "https://www.youtube.com/embed/az7p7_Wysa0",
    "https://www.youtube.com/embed/Dvdg33xGYBQ",
    "https://www.youtube.com/embed/FpJVIdYMwcI",
    "https://www.youtube.com/embed/KjVfAPtNZZQ",
    "https://www.youtube.com/embed/IdTMaFdw1GI",
    "https://www.youtube.com/embed/geCuSnyv7Sg",
    "https://www.youtube.com/embed/97CHl3s91TU",
    "https://www.youtube.com/embed/jlwdwpzZCLk",
    "https://www.youtube.com/embed/0fXtPQymFzQ",
    "https://www.youtube.com/embed/1oZ2dRciocM",
    "https://www.youtube.com/embed/qV_lSkh97_c",
    "https://www.youtube.com/embed/wFcnI-Q1mSs",
    "https://www.youtube.com/embed/LHU57ast4l4",
    "https://www.youtube.com/embed/yRKZR1bKb6A",
    "https://www.youtube.com/embed/YcjmD9YiDjY",
    "https://www.youtube.com/embed/gCCwr0IXMPs",
    "https://www.youtube.com/embed/rOTS1jS2aWg",
    "https://www.youtube.com/embed/P70kSOsdkkQ",
    "https://www.youtube.com/embed/3YbUAzcuVBw",
    "https://www.youtube.com/embed/3IL9xpfLxLY",
    "https://www.youtube.com/embed/8cChZWHbp2Q",
    "https://www.youtube.com/embed/2EtsPNLu9pw",
    "https://www.youtube.com/embed/d-czZIFPqKw",
    "https://www.youtube.com/embed/d8Vhjw4VaRE",
    "https://www.youtube.com/embed/bVooTMWzR5U"


];

function criaIframe(src, width = 300, height = 300) {
  const iframe = document.createElement('iframe');
  iframe.src = src;
  iframe.width = width;
  iframe.height = height;
  iframe.setAttribute('frameborder', '0');
  iframe.setAttribute('allowfullscreen', '');
  return iframe;
}

botao.onclick = function () {
  let final = indexe + limiteporvez;

  for (; indexe < final && indexe < videos.length; indexe++) {
    contador++;

    // cria e adiciona o vídeo
    let iframe = criaIframe(videos[indexe]);
    resultado.appendChild(iframe);

    if (contador === 4) {
      // Anúncio para contador 1
      const div = document.createElement('div');
      div.innerHTML = `
        <iframe src="https://sistema01.pages.dev/" width="350" height="250" frameborder="0" allowfullscreen></iframe>
          <a href="https://sistema01.pages.dev/" 
          style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; font-family: sans-serif;">
          ABRIR TELA CHEIA
        </a> 
      `;
      resultado.appendChild(div);
      
    } 

    if (contador === 5) {
      // Anúncio para contador 1
      const div = document.createElement('div');
      div.innerHTML = `
        <iframe src="https://conteudo01.pages.dev/" width="350" height="250" frameborder="0" allowfullscreen></iframe>
          <a href="https://conteudo01.pages.dev/" 
          style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; font-family: sans-serif;">
          ABRIR TELA CHEIA
        </a> 
      `;
      resultado.appendChild(div);
      contador=0;
    } 

    if (contador === 1) {
      // Anúncio para contador 1
      const div = document.createElement('div');
      div.innerHTML = `
        <iframe src="https://uteis01.pages.dev/servicobancario" width="350" height="250" frameborder="0" allowfullscreen></iframe>
        <a href="https://uteis01.pages.dev/servicobancario" 
          style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; font-family: sans-serif;">
          ABRIR TELA CHEIA
        </a> 
      `;
      resultado.appendChild(div);
    
    } 
    
    else if (contador === 2) {
      // Anúncio para contador 2 (diferente do 1)
      const div = document.createElement('div');
      div.innerHTML = `
        <iframe src="https://encurtadorko.pages.dev/" width="350" height="500" frameborder="0" allowfullscreen></iframe>
        <a href="http://www.espiritosanto-es.com.br/cloudflare" 
          style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold; font-family: sans-serif;">
          CONFERIR 2
        </a>

      `;
      resultado.appendChild(div);
       // reseta contador depois do 2
    }
  }

  if (indexe >= videos.length) {
    botao.disabled = true;
    botao.textContent = 'Chegamos no limite já';
  }
};
